### PR TITLE
fix bad names for logs of observability

### PR DESCRIPTION
**Pull request by lu-xiaoshuang**

### CODE REVIEW

**Comment by wu-sheng** [comment]
I can't the point of breaking interface name.

**Comment by wu-sheng** [comment]
Why the kafka relative codes added under rename PR?

**Comment by lu-xiaoshuang** [comment]
> I can't the point of breaking interface name.

Appears that applications do most likely not use these classes since they are internal parts of the agent.

**Comment by lu-xiaoshuang** [comment]
> Why the kafka relative codes added under rename PR?

My fault. remove it.

**Review by liuhaoyang — APPROVED** [review]

**Pull request merged**
