### PR TITLE
Add kafka reporter

### PR DESCRIPTION
**Pull request by lu-xiaoshuang**
This pull request **SHALL** be merged after [557](https://github.com/SkyAPM/SkyAPM-dotnet/pull/557).

### CODE REVIEW

**Comment by liuhaoyang** [comment]
Activate this PR. Is there a way to test the accuracy of the kafka data reporting function, or can you provide screenshots for local testing?

**Comment by liuhaoyang** [comment]
Also, can you merge https://github.com/SkyAPM/SkyAPM-dotnet/pull/557 and this PR together?  then I will review and test the code

**Comment by lu-xiaoshuang** [comment]
> Also, can you merge #557 and this PR together? then I will review and test the code

Hi @liuhaoyang, this pull request already contains #557. :-)

**Comment by lu-xiaoshuang** [comment]
> Activate this PR. Is there a way to test the accuracy of the kafka data reporting function, or can you provide screenshots for local testing?

Hi @liuhaoyang, here are some snapshots.

segment in kafka message

kafka

`traceId: "4493e8179efcd36d936828454c0aa920.15.17035667172280003"
traceSegmentId: "4493e8179efcd36d936828454c0aa920.15.17035667172280004"
spans {
  parentSpanId: -1
  startTime: 1703566717228
  endTime: 1703566717228
  operationName: "/home/index"
  peer: "::1"
  spanLayer: Http
  componentId: 3001
  tags {
    key: "url"
    value: "http://localhost:5000/home/index"
  }
  tags {
    key: "path"
    value: "/home/index"
  }
  tags {
    key: "http.method"
    value: "GET"
  }
  tags {
    key: "status_code"
    value: "200"
  }
}
service: "dotnet-service-1"
serviceInstance: "a.b.c.d@75ffab866b6344a8bfa80688ddbb8258"`

**Comment by lu-xiaoshuang** [comment]
> Activate this PR. Is there a way to test the accuracy of the kafka data reporting function, or can you provide screenshots for local testing?

Hi @liuhaoyang , some logs for your reference:

`2023-12-26 12:58:30.100 +08:00 [dotnet-service-1] [Information] SkyApm.InstrumentStartup : Initializing ...
2023-12-26 12:58:30.103 +08:00 [dotnet-service-1] [Information] SkyApm.Service.RegisterService : Loaded instrument service [SkyApm.Service.RegisterService].
2023-12-26 12:58:30.104 +08:00 [dotnet-service-1] [Information] SkyApm.Service.LogReportService : Loaded instrument service [SkyApm.Service.LogReportService].
2023-12-26 12:58:30.104 +08:00 [dotnet-service-1] [Information] SkyApm.Service.PingService : Loaded instrument service [SkyApm.Service.PingService].
2023-12-26 12:58:30.104 +08:00 [dotnet-service-1] [Information] SkyApm.Service.SegmentReportService : Loaded instrument service [SkyApm.Service.SegmentReportService].
2023-12-26 12:58:30.104 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Loaded instrument service [SkyApm.Service.CLRStatsService].
2023-12-26 12:58:30.104 +08:00 [dotnet-service-1] [Information] SkyApm.Sampling.SimpleCountSamplingInterceptor : Loaded instrument service [SkyApm.Sampling.SimpleCountSamplingInterceptor].
2023-12-26 12:58:30.110 +08:00 [dotnet-service-1] [Information] SkyApm.Service.RegisterService : Reported Service Instance Properties[Service=dotnet-service-1,InstanceId=a.b.c.d@75ffab866b6344a8bfa80688ddbb8258].
2023-12-26 12:58:30.124 +08:00 [dotnet-service-1] [Information] SkyApm.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.AspNetCore].
2023-12-26 12:58:30.124 +08:00 [dotnet-service-1] [Information] SkyApm.InstrumentStartup : Started SkyAPM .NET Core Agent.
2023-12-26 12:58:34.339 +08:00 [dotnet-service-1] [Information] SkyApm.Transport.Kafka.V8.LogReporter : Report 5 logs. cost: 00:00:01.2191414s
2023-12-26 12:58:37.184 +08:00 [dotnet-service-1] [Information] SkyApm.Transport.Kafka.V8.SegmentReporter : Report 1 trace segment. cost: 00:00:01.0676389s
2023-12-26 12:58:39.293 +08:00 [dotnet-service-1] [Information] SkyApm.Transport.Kafka.V8.SegmentReporter : Report 3 trace segment. cost: 00:00:00.1672816s
2023-12-26 12:59:00.113 +08:00 [dotnet-service-1] [Information] SkyApm.Service.PingService : Ping server @2023-12-26 04:59:00 +00:00
2023-12-26 12:59:00.285 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 8M ThreadPool 32765 32767 1000 1000
2023-12-26 12:59:30.208 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 9M ThreadPool 32763 32767 1000 1000
2023-12-26 13:00:00.117 +08:00 [dotnet-service-1] [Information] SkyApm.Service.PingService : Ping server @2023-12-26 05:00:00 +00:00
2023-12-26 13:00:00.177 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 9M ThreadPool 32765 32767 1000 1000
2023-12-26 13:00:30.166 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 10M ThreadPool 32763 32767 1000 1000
2023-12-26 13:01:00.115 +08:00 [dotnet-service-1] [Information] SkyApm.Service.PingService : Ping server @2023-12-26 05:01:00 +00:00
2023-12-26 13:01:00.174 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 10M ThreadPool 32763 32767 1000 1000
2023-12-26 13:01:30.170 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 11M ThreadPool 32763 32767 1000 1000
2023-12-26 13:02:00.113 +08:00 [dotnet-service-1] [Information] SkyApm.Service.PingService : Ping server @2023-12-26 05:02:00 +00:00
2023-12-26 13:02:00.173 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 11M ThreadPool 32766 32767 1000 1000
2023-12-26 13:02:30.167 +08:00 [dotnet-service-1] [Information] SkyApm.Service.CLRStatsService : Report CLR Stats. CPU UsagePercent 0 GenCollectCount 0 0 0 12M ThreadPool 32763 32767 1000 1000
`

**Comment by wu-sheng** [comment]
> > Also, can you merge #557 and this PR together? then I will review and test the code
> 
> Hi @liuhaoyang, this pull request already contains #557. :-)

So, we should close #557?

**Comment by wu-sheng** [comment]
No activity, close for now.

**Comment by lu-xiaoshuang** [comment]
> No activity, close for now.

for what?

**Pull request closed without merging**
