### PR TITLE
Support access to ITracingContext through static property.

### PR DESCRIPTION
**Pull request by inversionhourglass**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
The current pr adds the SkyApm.Utilities.StaticAccessor project, which provides static properties for accessing `ITracingContext`, which is convenient for creating a `Segment` in a static method.
有时候我们需要在静态方法中创建`segment`，当前PR中的SkyApm.Utilities.StaticAccessor项目提供了静态属性访问`ITracingContext`

```csharp
// 1. add SkyApm.Utilities.StaticAccessor package reference
// dotnet add package SkyApm.Utilities.StaticAccessor

// 2. enable in startup
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        // ...

        services.AddSkyAPMStaticAccessor();
    }
}

// 3. use it in static method
static async Task M()
{
    var context = SkyApm.Utilities.StaticAccessor.TracingContext.CreateLocalSegmentContext("test");
    await Task.Delay(100);
    SkyApm.Utilities.StaticAccessor.TracingContext.Release(context);
}
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
@liuhaoyang I am not sure whether this is a good way to access the agent kernel. This looks like direct accessing. Usually, we should think the agent could be removed at any moment. The API bridge should be able to fall back to no agent mode.

**Comment by inversionhourglass** [comment]
> Usually, we should think the agent could be removed at any moment. The API bridge should be able to fall back to no agent mode.

In the new commit, I added processing logic, even if the agent is disabled(by remove environment), there will be no error because of this function. Of course, if @liuhaoyang thinks that this function can be added to `AddSkyAPMCore` as a default extension, then the second step(enable in startup) also be omitted.

在新的提交中我增加了处理逻辑，即使agent被禁用了也不会因为该功能而出现错误，当然如果 @liuhaoyang 认为该功能可以添加到 `AddSkyAPMCore` 中作为一个默认的扩展，那么第二步的startup中的代码也可以省略。

**Comment by wu-sheng** [comment]
Let's wait for @liuhaoyang

**Comment by liuhaoyang** [comment]
Good idea! I will review the code tomorrow.

**Review by liuhaoyang — APPROVED** [review]

**Pull request merged**
