### PR TITLE
Support azure-pipelines github release and Introduce SegmentContextScopeManager

### PR DESCRIPTION
**Pull request by caozhiyuan**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

___
### New feature or improvement
- support azure-pipelines github release , like this https://github.com/caozhiyuan/SkyAPM-dotnet/releases , need config azure-pipelines

setting:
QQ截图20190331171203

- Introduce SegmentContextScopeManager

### CODE REVIEW

**Comment by liuhaoyang** [comment]
image
What is gac?

**Comment by caozhiyuan** [comment]
an util cmd use to register gac dll. if not use SkyApm.DotNet.Installer.msi to install , just use SkyApm.DotNet.Installer.zip to self install on windows @liuhaoyang

**Comment by caozhiyuan** [comment]
only need 
  gacutil.exe /i %DLLPATH%\SkyApm.ClrProfiler.Trace.dll
   gacutil.exe /i %DLLPATH%\SkyApm.Abstractions.dll
   gacutil.exe /i %DLLPATH%\netstandard.dll
above code ensure run in admin

**Comment by liuhaoyang** [comment]
Where is GAC util downloaded or compiled?

**Comment by caozhiyuan** [comment]
copy from windows net461 sdk. @liuhaoyang   
this path C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools

**Comment by wu-sheng** [comment]
> copy from windows net461 sdk.

Could you use a download instead of a copy? Because copy means rehost source codes or dist. And no binary is allowed in source release.

**Comment by caozhiyuan** [comment]
@wu-sheng  because windows server no gacutil.exe . now , built it from myself code (https://github.com/caozhiyuan/SkyAPM-dotnet/blob/coreclr_profiler/tools/gacutil/Program.cs), it need change it's name ? 
@liuhaoyang gac.cmd gacuitl.exe reomved from installer , in windows recommend use SkyApm.DotNet.Installer.msi

**Comment by wu-sheng** [comment]
If [this](https://github.com/caozhiyuan/SkyAPM-dotnet/blob/coreclr_profiler/tools/gacutil/Program.cs) is written by yourself, then it is fine. If you copy and nearly copy from somewhere(which should in Apache or MIT license), then LICENSE file needs to be updated.

The basic principle is very simple, 3rd party code copy is not recommended, try any possible way to avoid it. If you have to copy it, make sure license supports that and LICENSE file of source updated.

**Comment by caozhiyuan** [comment]
code from https://docs.microsoft.com/en-us/dotnet/api/system.enterpriseservices.internal.publish.gacinstall?view=netframework-4.7.2 , just minimality

**Comment by liuhaoyang** [comment]
@caozhiyuan Can we consider changing our mind? We can also try to load the required dll when the agent is started.

**Comment by caozhiyuan** [comment]
@liuhaoyang  yes , may be , but has a problem is dll reference lost , if reflect to get types may rasise error. now, just  SkyApm.ClrProfiler.Trace.AspNetCore need dll reference 
https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/src/SkyApm.ClrProfiler.Trace.AspNetCore/SkyApm.ClrProfiler.Trace.AspNetCore.csproj

**Comment by liuhaoyang** [comment]
> @liuhaoyang yes , may be , but has a problem is dll reference lost , if reflect to get types may rasise error. now, just SkyApm.ClrProfiler.Trace.AspNetCore need dll reference
> https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/src/SkyApm.ClrProfiler.Trace.AspNetCore/SkyApm.ClrProfiler.Trace.AspNetCore.csproj

So how do we solve the dll version conflict problem? Just for example, our plugin uses stackexchange.redis v1.2, and the user depends on stackexchange.redis v1.0, in which case the user will throw an exception that `cannot find the dll`.

**Comment by caozhiyuan** [comment]
we don't ref stackexchange.redis . https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/src/SkyApm.ClrProfiler.Trace.StackExchangeRedis/SkyApm.ClrProfiler.Trace.StackExchangeRedis.csproj

just reflect  to get method or type.
https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/src/SkyApm.ClrProfiler.Trace.StackExchangeRedis/StackExchangeRedis.cs#L49

Usually assembly high versions are downward compatible.

i think it can load the required dll when the agent is started.  like this : https://github.com/caozhiyuan/DotNetty/blob/dev/src/DotNetty.Rpc/Service/AssemblyManager.cs，

so we could first load all deps dll , so will not rasie dll not found (if raise just skip).

**Comment by caozhiyuan** [comment]
@liuhaoyang  had load the all trace dll when the agent is started.  no need load deps dll , corelib will load deps dll.

**Comment by wu-sheng** [comment]
> code from https://docs.microsoft.com/en-us/dotnet/api/system.enterpriseservices.internal.publish.gacinstall?view=netframework-4.7.2 , just minimality , because GacRemove no return , changed for show GacRemoveStatus

Is it MIT license?

**Comment by caozhiyuan** [comment]
yes , just IAssemblyCache  interface , i think no need add license.  link : 
https://github.com/Microsoft/referencesource

@wu-sheng

**Comment by wu-sheng** [comment]
`IAssemblyCache` interface is also the code. That is the basic rule. And the repo says, it is MIT, then we need to treat them as MIT licensed. Definitely, LICENSE required.

**Comment by caozhiyuan** [comment]
@liuhaoyang  please review SegmentContextScopeManager , if ok , merge it. and this feature is over . look at you later.

@wu-sheng because gac COM some problem , i use .net sdk method , no LICENSE problem.

**Pull request merged**
