### PR TITLE
Use Dictionary to prevent m*n string comparison

### PR DESCRIPTION
**Pull request by pengweiqhca**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [X] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Use Dictionary to prevent m*n string comparison

### CODE REVIEW

**Comment by liuhaoyang** [comment]
Why do you want to make these changes? @pengweiqhca

**Comment by pengweiqhca** [comment]
`TracingDiagnosticMethod.Invoke` may be executed multiple times, , even if diagnosticName don't match

**Comment by liuhaoyang** [comment]
`TracingDiagnosticMethod.invoke` does not mean that the real `method.Invoke` will be executed, and the `DiagnosticName` is also verified in the TracingDiagnosticMethod.

**Comment by pengweiqhca** [comment]
If use `Dictionary`, performance will be better

**Comment by liuhaoyang** [comment]
Please give the benchmark result

**Pull request closed without merging**
