### PR TITLE
fetch the latest protocol commit

### PR DESCRIPTION
**Pull request by liuhaoyang**
Please answer these questions before submitting pull request
fetch the latest protocol commit

### CODE REVIEW

**Comment by wu-sheng** [comment]
So, we removed the support for previous protocol? I remember we have v6 and v8 supports right now, right?

**Comment by wu-sheng** [comment]
I see, then it is reasonable to remove. I have known a lot of users set this config wrong(sw6), and were confused.

**Comment by wu-sheng** [comment]
Notice, the roamap.md and link in the readme should be updated.

**Comment by liuhaoyang** [comment]
> Notice, the roamap.md and link in the readme should be updated.

I will update them later in other pr,  let me think about what features to do next ...

**Comment by wu-sheng** [comment]
> > Notice, the roamap.md and link in the readme should be updated.
> 
> I will update them later in other pr, let me think about what features to do next ...

Sure, it is fine to remove them. We don't maintain any roadmap even for the main repo :) Things are not predictable.

**Review by wu-sheng — DISMISSED** [review]

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
