### PR TITLE
Improve performance: Use struct

### PR DESCRIPTION
**Pull request by pengweiqhca**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [X] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Use struct

### CODE REVIEW

**Comment by liuhaoyang** [comment]
Have you done benchmark test?

**Comment by pengweiqhca** [comment]
class:

|   Method |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
| --------- | --------- | --------- | --------- | ------- | ------ | ------ | ---------- |
| Generate | 100.8 ns | 1.971 ns | 2.889 ns | 0.0094 |     - |     - |      40 B |

struct:

|   Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|---------:|---------:|------:|------:|------:|----------:|
| Generate | 98.03 ns | 2.383 ns | 2.229 ns |     - |     - |     - |         - |

**Comment by liuhaoyang** [comment]
@pengweiqhca If you are interested, can you add benchmark tests to more APIs?

**Comment by wu-sheng** [comment]
Interesting PR, I like this.

**Comment by caozhiyuan** [comment]
i think should test with class SegmentContext  . this benchmark : class on heap , and struct on thread stack. 
@pengweiqhca

**Comment by caozhiyuan** [comment]
use class better , because SegmentContext  has two uniqueid  (48 bytes, recomend 24 bytes on 64-bit platforms) and this struct can't be ref struct. @pengweiqhca

**Pull request merged**
