### PR TITLE
Add ClrProfiler ILRewrite Test

### PR DESCRIPTION
**Pull request by caozhiyuan**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] New feature provided
___
### New feature or improvement
- add profiler il rewrite test
- improve azure-pipelines

### CODE REVIEW

**Comment by caozhiyuan** [comment]
@liuhaoyang  add profiler il rewrite test , improve azure-pipelines , i merged it . when you free time , you look it.

**Comment by liuhaoyang** [comment]
You can merge directly on the coreclr_profiler branch. In addition, I have some suggestions, before adding features, you can create an issue and describe in detail what needs to be done.

**Comment by caozhiyuan** [comment]
and profiler c++ csproj changed on last PR , need run vcpkg integrate install

**Comment by caozhiyuan** [comment]
@liuhaoyang  ok . next need do some skyapm integration test , or just test it manually and watch skywalking admin view?

**Comment by liuhaoyang** [comment]
Java agent has done integration test. @ascrutae can you tell us something about it?

**Comment by caozhiyuan** [comment]
@liuhaoyang  ilrepack tool has dllsign problem in this RP , i will fix it later.

**Pull request merged**
