### PR TITLE
Add github action to run BUILD and TEST

### PR DESCRIPTION
**Pull request by liuhaoyang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by wu-sheng** [comment]
This will only run after the first merge.

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
CI fails, please fix through a new pull request.

**Comment by liuhaoyang** [comment]
Sorry, I am still testing this pr. I will submit a new pull request later

**Comment by wu-sheng** [comment]
> Sorry, I am still testing this pr. I will submit a new pull request later

I have to merge before GHA wouldn't work until this file exists in the master branch

**Pull request merged**
