### PR TITLE
Introduce SegmentcontextScope and some Improve 

### PR DESCRIPTION
**Pull request by caozhiyuan**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [x] Improve performance

- Related issues

___
### Bug fix
- Bug description.
https://github.com/SkyAPM/SkyAPM-dotnet/pull/175#issuecomment-478224718

- How to fix?
Use Peer

___
### New feature or improvement
- Describe the details and related test reports.

* Introduce SegmentcontextScope (need test a lot)
* StringOrIntValueHelpers ParseStringOrIntValue Just Use SubString
* SkyApm.Sample.AspNet project change to PackageReference

### CODE REVIEW

**Comment by caozhiyuan** [comment]
SegmentContextAccessor be removed , https://github.com/linkinshi/SkyAPM-dotnet-mysql need update to lastest.

**Comment by wu-sheng** [comment]
Why Mysql plugin is in another repo?

**Comment by liuhaoyang** [comment]
In previous versions, I also used SegmentContextAsyncLocalScope to manage the current Segment. But in asynchronous scenarios, it raises some bug .. https://github.com/SkyAPM/SkyAPM-dotnet/issues/102 https://github.com/SkyAPM/SkyAPM-dotnet/issues/72

**Comment by liuhaoyang** [comment]
> Why Mysql plugin is in another repo?

Mysql.Data lib is under the GPL license. Uh. I am worried that it will lead to incompatibility of the license.

**Comment by wu-sheng** [comment]
If it is compiled level, it is fine. SkyWalking has mysql plugin as default. But if your binary requires that, that is another story.

In my mind, plugin only works after user use it, so, in that case, you don't include/depend mysql, user does.

**Comment by caozhiyuan** [comment]
@liuhaoyang  https://github.com/caozhiyuan/SkyAPM-dotnet/blob/0.7.0/src/SkyWalking.Core/Context/TracingContext.cs#L48 
no scope , this stack is not safe in multi-thread.

**Comment by caozhiyuan** [comment]
i want to merge span in one segmentcontext, but it need some time .  now , one span one segmentcontext, but it sample.

**Comment by wu-sheng** [comment]
For multiple thread case, I highly recommend you ref SkyWalking javaagent did for vertx. That is 100% async framework, and it works perfectly with our new API.

**Comment by liuhaoyang** [comment]
@caozhiyuan  I have discussed with sheng about the problem of segment. Letting each span as a segment is my compromise in the C# Async syntax.

**Comment by liuhaoyang** [comment]
> @liuhaoyang https://github.com/caozhiyuan/SkyAPM-dotnet/blob/0.7.0/src/SkyWalking.Core/Context/TracingContext.cs#L48
> no scope , this stack is not safe in multi-thread.

Each request is a scope...

**Comment by caozhiyuan** [comment]
@liuhaoyang  like this : https://github.com/SkyAPM/SkyAPM-dotnet/blob/coreclr_profiler/sample/SkyApm.Sample.AspNetCore/Controllers/HomeController.cs#L38

**Comment by caozhiyuan** [comment]
@liuhaoyang run SkyApm.Sample.Frontend.Controllers  http://localhost:5001/api/values/2 test it. it diff with  previous versions.

**Comment by caozhiyuan** [comment]
@liuhaoyang  any problem about SegmentContextScope ?

**Pull request closed without merging**
