### PR TITLE
Add span structure

### PR DESCRIPTION
**Pull request by inversionhourglass**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.
`Local SegmentContext` can only be mounted to `Entry SegmentContext`
```csharp
[HttpGet]
[Route("/test")]
public async Task<string> Get()
{
    var parentLocalSegment = _tracingContext.CreateLocalSegmentContext("parent");

    var childLocalSegment = _tracingContext.CreateLocalSegmentContext("child");
    _tracingContext.Release(childLocalSegment);

    _tracingContext.Release(parentLocalSegment);

    return "ok";
}
```
image
- How to fix?
Comment the following line.

https://github.com/SkyAPM/SkyAPM-dotnet/blob/8cfe8e8ee421c2287f514f69804a423944dd1920/src/SkyApm.Core/Tracing/SegmentContextFactory.cs#L231

after comment:
image

___
### New feature or improvement
- Describe the details and related test reports.
#### Span Structure
Our current logic is to create a `SegmentContext` for each `span`. This can indeed handle the complex async/await in .NET, but the `segmentId` cannot be sorted, which will cause our trace to look out of order.
```csharp
[HttpGet]
[Route("multiRequest")]
public async Task<string> MultiRequest()
{
    await HttpPostAsync(1);
    await HttpPostAsync(2);
    await HttpPostAsync(3);
    await HttpExceptionAsync();
    await HttpPostAsync(5);


    return "12345";
}
```
image

I spent some time writing a set of interfaces based on `span` as the main structure. The structure can be switched by configuration `SkyWalking:StructType`. The default value is `segment`, you can change to `span`. The span structure is not perfect. In some cases, it will be ugly. The following is an introduction to various situations.

1. general case
The example I gave you at the beginning.
image
This is the best and simplest example and everything works fine.

2. async method does not have await, but completes before parent span completes
```csharp
[HttpGet]
[Route("notAwaitedOnTime")]
public async Task<string> NotAwaitedOnTime()
{
    WrappedHttpDelayAsync(1000);


    await DelayAsync(nameof(NotAwaitedOnTime), 500);


    await WrapDelay(1000);


    return nameof(NotAwaitedOnTime);
}
```
image
There's nothing wrong with this.

3. async method has no await and neither completes when parent span complete
```csharp
[HttpGet]
[Route("notAwaitedOutofTime")]
public async Task<string> NotAwaitedOutofTime()
{
    WrappedHttpDelayAsync(2000);


    await WrapDelay(100);


    await DelayAsync(string.Empty, 200);


    return nameof(NotAwaitedOutofTime);
}
```
image
As you see, `HttpDelayWrap` and `http://127.0.0.1:5001/test/delay` is marked as `[async]`, because they are not completed before the parent span to complete.

4. The async method has no await and is completed a long time after the parent span has completed
```csharp
[HttpGet]
[Route("notAwaitedOutofMergeTime")]
public async Task<string> NotAwaitedOutofMergeTime()
{
    WrappedHttpDelayAsync(10000);


    await WrapDelay(700);


    await DelayAsync(string.Empty, 200);


    return nameof(NotAwaitedOutofMergeTime);
}
```
image
As you see, in addition to the `[async]` flag, there are flags like `[async-1]`, and `WrappedHttpDelayAsync-after` becomes their child span. In fact, this is what it looks like without await. The result of case 3 is merged by [AsyncSpanCombiner](https://github.com/inversionhourglass/SkyAPM-dotnet/blob/master/src/SkyApm.Core/Tracing/AsyncSpanCombiner.cs). Because of `AsyncSpanCombiner`, the generated trace data will be delayed and reported to the oap-server for a period of time. This time can be configured through `SkyWalking:SpanStructure:MergeDelay`, the default is 5000(ms).

5. not await and not await
```csharp
[HttpGet]
[Route("deeplyNotAwaited")]
public string DeeplyNotAwaited()
{
    OuterAsync();
    return nameof(DeeplyNotAwaited);


    async Task OuterAsync()
    {
        var outer = _tracingContext.CreateLocal("outer");


        await DelayAsync(nameof(OuterAsync), 1000);
        InnerAsync();


        _tracingContext.Finish(outer);
    }


    async Task InnerAsync()
    {
        var inner = _tracingContext.CreateLocal("inner");


        await DelayAsync(nameof(InnerAsync), 10000);
        _tracingContext.Finish(_tracingContext.CreateLocal("inner-step1"));
        await HttpDelayAsync(100);


        _tracingContext.Finish(inner);
    }
}
```
image
This code will generate three segments, the first two have shorter intervals, so the second will be merged into the first, and the third interval exceeds the merge wait time, so no merge is performed, but the third associated parent The segment is the second, and the second is merged into the first, so the third cannot find the parent segment.

You can find more test case in [TestController](https://github.com/inversionhourglass/SkyAPM-dotnet/blob/master/sample/SkyApm.Sample.Frontend/Controllers/TestController.cs).

Compared with `SegmentContext`, `Span` can guarantee order and can produce less segment data, but as in the previous example, some cases will produce extra nodes (as [async-1] in example 4), some cases can cause traces to not be associated (as in example 5). In addition, not all data will be delayed in merge, only if there are asynchronous incomplete subtasks. 

#### UI changes
This feature may cause the spanId in the same segment to be discontinuous. In the current UI version 8.x, there is a logic to check the continuous spanId, so I additionally modified part of the logic of rocketbot-ui and submitted a [pullrequest](https://github.com/apache/skywalking-rocketbot-ui/pull/571).

#### Interface changes
In this feature, I marked `ITracingContext.CreateEntrySegmentContext`, `ITracingContext.CreateLocalSegmentContext`, `ITracingContext.CreateExitSegmentContext`, `ITracingContext.Release` as [Obsolete], it will be replaced with `ITracingContext.CreateEntry`, `ITracingContext.CreateLocal`, `ITracingContext.CreateExit`, `ITracingContext.Finish` and it will decide whether the main structure is `SegmentSpan` or `SegmentContext` according to the configuration.

#### Threading Extensions
In order to avoid the situation in examples 4 and 5, we can manually place the asynchronous non-await method into a task, and then associate the task with the current segment as a new segment. In order to simplify the operation of creating a segment, right The threading series of classes have been extended.
```csharp
[HttpGet]
[Route("backgroundSkyApmTask")]
public string BackgroundSkyApmTask()
{
    SkyApmTask.Run(() =>
    {
        var outer = _tracingContext.CreateLocal($"BackgroundSkyApmTask-outer");
        SkyApmTask.Run(() =>
        {
            var inner = _tracingContext.CreateLocal($"BackgroundSkyApmTask-inner");
            Thread.Sleep(1000);
            _tracingContext.Finish(_tracingContext.CreateLocal($"BackgroundSkyApmTask-.Instantaneous"));
            _tracingContext.Finish(inner);
        });
        Thread.Sleep(1000);
        _tracingContext.Finish(outer);
    });
    Thread.Sleep(500);
    return nameof(BackgroundSkyApmTask);
}
```

#### Static Accessor
Sometimes we may need to create spans in static methods or where IoC cannot be used (such as Threading Extensions), so I created [SkyApmInstances](https://github.com/inversionhourglass/SkyAPM-dotnet/blob/master/src/SkyApm.Utilities.StaticAccessor/SkyApmInstances.cs), which can access the `ITracingContext` through `SkyApmInstances.TracingContext`. To use this feature, you need to refer to `SkyApm.Utilities.StaticAccessor` and Register in startup `services.AddSkyAPMStaticAccessor();`.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@inversionhourglass Could you separate this PR to several separates? It is very uncertain to review such a large pull request having 3k LOC.

**Comment by inversionhourglass** [comment]
@wu-sheng Is it grouped by commit? Some commit bugs have been fixed in subsequent commits, will this affect your review?

**Comment by wu-sheng** [comment]
You could submit pull requests one by one if there are dependencies. Take the time. 
It is better to have small improvements, rather than unexpected unstable after big updates.

**Comment by wu-sheng** [comment]
Separating features/fixes in different pull requests could push you harder to get the boundaries clear, and make the code changes more clear focusing on it is own purpose.

**Comment by wu-sheng** [comment]
If this can't catch up with the 2.0 release, we could have more 2.x releases in the future.

**Pull request closed without merging**
