### PR TITLE
refactoring for SkyApm.Transport.Protocol

### PR DESCRIPTION
**Pull request by lu-xiaoshuang**
- Why submit this pull request?
- [*] refactoring

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please fix the CI.

**Comment by lu-xiaoshuang** [comment]
CI issue fixed

**Comment by wu-sheng** [comment]
Mark this on 2.3.0, as @liuhaoyang is planning to run 2.2.0 release, we should stop adding new things.

**Comment by lu-xiaoshuang** [comment]
Hi @liuhaoyang , would you please review this pull request?

**Comment by wu-sheng** [comment]
Why do we need this? Please explain your proposal.

**Comment by lu-xiaoshuang** [comment]
> Why do we need this? Please explain your proposal.

reporter interface layer needs an independent dotnet project. Both gRPC reporter and Kafka reporter are concrete implementations which live in their own project directories.

**Comment by wu-sheng** [comment]
We don't have Kafka reporter AFAIK. Nother to be shared.

**Comment by lu-xiaoshuang** [comment]
> We don't have Kafka reporter AFAIK. Nother to be shared.

https://github.com/SkyAPM/SkyAPM-dotnet/pull/559

**Comment by wu-sheng** [comment]
That thing had no progress for over half of the year. So, I closed that.

I don't know what happened.

**Comment by lu-xiaoshuang** [comment]
> That thing had no progress for over half of the year. So, I closed that.
> 
> I don't know what happened.

What about this plan for kafka reporter?

1. merge #584 @wu-sheng 
2. reopen #559 @wu-sheng 
3. update #559 @lu-xiaoshuang 
4. merge #559 @liuhaoyang

**Comment by wu-sheng** [comment]
All others are closed, how close are they ready to be accepted? @liuhaoyang

**Review by liuhaoyang — APPROVED** [review]

**Comment by wu-sheng** [comment]
@lu-xiaoshuang We have merged this, please update reporter part.

**Comment by lu-xiaoshuang** [comment]
> @lu-xiaoshuang We have merged this, please update reporter part.

Copy. Please reopen #559 ~

**Comment by wu-sheng** [comment]
You could open a new one with a clear context and including this change.

**Comment by lu-xiaoshuang** [comment]
> You could open a new one with a clear context and including this change.

okay.

**Pull request merged**
