### PR TITLE
bugfix: Info of Inner Exception lost.

### LINKED ISSUE #390: Stacktrace of the Inner Exception got lost
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- SkyApm-v1.1.0

- What happen?
Stacktrace of the Inner Exception got lost

### PR DESCRIPTION
**Pull request by snakorse**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
Closes #390 
___
### Bug fix
- Info of Inner Exception lost.

- How to fix?
Fixed exception tree looks like below:
image

### CODE REVIEW

**Review by zeaposs — APPROVED** [review]
With enough of inner exception, stack trace can get pretty big. Maybe we could add an option to limit demystified log to last x lines / store only first and last line of every excetion except fthe innermost.

**Comment by wu-sheng** [comment]
> With enough of inner exception, stack trace can get pretty big. Maybe we could add an option to limit demystified log to last x lines / store only first and last line of every excetion except fthe innermost.

Agree. We have this in the Java agent, the threshold could be the length of lines, or the chars.

@snakorse Please recheck the CI.

**Comment by snakorse** [comment]
I agree with that too, and limit the inner exception depth could also be a choice.
But there is an problem to letting the user to config the limitation value: the `ErrorOccurred()` method is an extension method which can not follow the DI convention to resolve the user configuration, any idea about this? @zeaposs 
As exception with many inner exceptions case rarely happen, maybe we can just give an internal const limitation value, for example 5 or 10 depth.

**Comment by zeaposs** [comment]
@snakorse We could create a separate DI type `IExceptionDemystifier` or `IExceptionProcessor`, which in turn would have an access to `IConfigAccessor`. This object would return `LogEvent` type object generated from a provided exception. This way we could replace second parameter for `ErrorOccurred` from `Exception` to `LogEvent`.

The default depth limitation of 5 is good imo, although we'll still get a big log size for sites that use recurrency (yeah, seen websites doing that). That's why I think character/line threshold is better.

**Comment by snakorse** [comment]
> @snakorse We could create a separate DI type `IExceptionDemystifier` or `IExceptionProcessor`, which in turn would have an access to `IConfigAccessor`. This object would return `LogEvent` type object generated from a provided exception. This way we could replace second parameter for `ErrorOccurred` from `Exception` to `LogEvent`.

That's a reasonable sln, but changing the function signature could lead big change,  we must also consider about the backword compatibility and ensure the developer-user can easily use it, beacuse it's the diagnostic componet developer who call this `ErrorOccurred` method.  We may should keep the existing `ErrorOccurred(span, exception)` method and mark it as Obsolete, and add a new overload method like  `ErrorOccurred(span, IExceptionProcessor)` , the `IExceptionProcessor` as a explicit parameter to notify the developer to dependency on a `IExceptionProcessor` from DI. 

> The default depth limitation of 5 is good imo, although we'll still get a big log size for sites that use recurrency (yeah, seen websites doing that). That's why I think character/line threshold is better.

I think the character/line threshold is more suite at LogEvent level, at the exception level, the depth limitation seems more reasonable.

**Comment by zeaposs** [comment]
> > @snakorse We could create a separate DI type `IExceptionDemystifier` or `IExceptionProcessor`, which in turn would have an access to `IConfigAccessor`. This object would return `LogEvent` type object generated from a provided exception. This way we could replace second parameter for `ErrorOccurred` from `Exception` to `LogEvent`.
> 
> That's a reasonable sln, but changing the function signature could lead big change, we must also consider about the backword compatibility and ensure the developer-user can easily use it, beacuse it's the diagnostic componet developer who call this `ErrorOccurred` method. We may should keep the existing `ErrorOccurred(span, exception)` method and mark it as Obsolete, and add a new overload method like `ErrorOccurred(span, IExceptionProcessor)` , the `IExceptionProcessor` as a explicit parameter to notify the developer to dependency on a `IExceptionProcessor` from DI.
> 
I agree.
> > The default depth limitation of 5 is good imo, although we'll still get a big log size for sites that use recurrency (yeah, seen websites doing that). That's why I think character/line threshold is better.
> 
> I think the character/line threshold is more suite at LogEvent level, at the exception level, the depth limitation seems more reasonable.

In worst case scenario we'll implement character/line threshold when we'll actually have a problem with the error logs being too big.

**Comment by snakorse** [comment]
@zeaposs I have made the change based on our discussion, with some changes that letting the `ErrorOccurred()` mehod dependent on `TracingConfig` directly instead of introducing the `IExceptionProcessor` which seems something heavy. Please do a review.

**Comment by zeaposs** [comment]
@snakorse Yeah, this will work too. I was thinking about that approach too at the beggining, but it looks like I overthinked that.

**Review by zeaposs — APPROVED** [review]

**Pull request merged**
