### PR TITLE
Refactor tracing context 

### PR DESCRIPTION
**Pull request by liuhaoyang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues

___
### Bug fix
- Bug description.
https://github.com/OpenSkywalking/skywalking-netcore/issues/102
- How to fix?
Every possible cross-threaded ExitSpan, as a new traceSegment

___
### New feature or improvement
- Describe the details and related test reports.
Redesign the tracing context api to support asp.net and wcf

### CODE REVIEW

**Comment by liuhaoyang** [comment]
This PR is in progress, please do not merge first. I will redesign the api of the tracing context, which will be a tedious task. In order to facilitate the code review, I opened this PR in advance.

**Comment by wu-sheng** [comment]
Got it. Take your time.

**Comment by liuhaoyang** [comment]
CI has been repaired.

**Comment by liuhaoyang** [comment]
Fix https://github.com/SkyAPM/SkyAPM-dotnet/issues/121, support concurrent operation

**Comment by liuhaoyang** [comment]
It’s really exciting. The core functionality of v0.8 has been completed.

**Pull request merged**
