### PR TITLE
feature: support span structure

### PR DESCRIPTION
**Pull request by inversionhourglass**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### New feature or improvement
- Describe the details and related test reports.
#### Span Structure
Our current logic is to create a `SegmentContext` for each `span`. This can indeed handle the complex async/await in .NET, but the `segmentId` cannot be sorted, which will cause our trace to look out of order.
```csharp
[HttpGet]
[Route("multiRequest")]
public async Task<string> MultiRequest()
{
    await HttpPostAsync(1);
    await HttpPostAsync(2);
    await HttpPostAsync(3);
    await HttpExceptionAsync();
    await HttpPostAsync(5);


    return "12345";
}
```
image

I spent some time writing a set of interfaces based on `span` as the main structure. Now you can use `ITracingContext.CreateEntrySpan`, `ITracingContext.CreateLocalSpan` and `ITracingContext.CreateExitSpan` to create a `SegmentSpan` instand of a `SegmentContext` that contains only one span. And use `ITracingContext.StopSpan` to finish a span.

#### Controlled experiment:
```csharp
var segmentContext = _tracingContext.CreateLocalSegmentContext("outer");
_tracingContext.Release(_tracingContext.CreateLocalSegmentContext("op-1"));
_tracingContext.Release(_tracingContext.CreateLocalSegmentContext("op-2"));
_tracingContext.Release(_tracingContext.CreateLocalSegmentContext("op-3"));
_tracingContext.Release(_tracingContext.CreateLocalSegmentContext("op-4"));
_tracingContext.Release(_tracingContext.CreateLocalSegmentContext("op-5"));
_tracingContext.Release(segmentContext);
```
image
```csharp
var span = _tracingContext.CreateLocalSpan("outer");
_tracingContext.StopSpan(_tracingContext.CreateLocalSpan("op-1"));
_tracingContext.StopSpan(_tracingContext.CreateLocalSpan("op-2"));
_tracingContext.StopSpan(_tracingContext.CreateLocalSpan("op-3"));
_tracingContext.StopSpan(_tracingContext.CreateLocalSpan("op-4"));
_tracingContext.StopSpan(_tracingContext.CreateLocalSpan("op-5"));
_tracingContext.StopSpan(span);
```
image

#### UI changes
This feature may cause the spanId in the same segment to be discontinuous. In the current UI version 8.x, there is a logic to check the continuous spanId, so I additionally modified part of the logic of rocketbot-ui and submitted a [pullrequest](https://github.com/apache/skywalking-rocketbot-ui/pull/571).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Hi, I would like to discuss this as I notice you are mentioning span ID is not continuous. Is this caused by segment's spans across threads? We actually expect span IDs are continues and from zero.

**Comment by wu-sheng** [comment]
There are 2 styles of building trace context. In Java, trace context exists in one thread only, which could guarantee no-lock in span ID generation. Another is Golang, it uses an optimistic locking mechanism to generate IDs in various threads(goroutine), but is still continuous.

**Comment by inversionhourglass** [comment]
In my opinion, if span is used as the main structure, the span id cannot be guaranteed to be continuous. The main reason is that the asyn method allows no await. Consider the following situation
```csharp
[HttpGet]
[Route("notAwait")]
public async Task<string> NotAwait()
{
    // aspnetcore diagnostic will generate an entry span and span id is set to 0
    CallAsync();
}

private async Task CallAsync()
{
    // The following local span id is 1
    var span = _tracingContext.CreateLocalSpan("callAsync");
    // The following http request will generate an exit span and span id is set to 2
    await HttpGetAsync();

    // The following http request will generate an exit span and span id is set to 3
    // The span id obtained downstream through the carrier is 3
    // Because of CallAsync has not be awaited, so the following exit span will be transferred to the new segment
    // If change the span id in new segment, then the downstream segment will not be able to find the corresponding span
    await HttpGetAsync();

    _tracingContext.StopSpan(span);
}
```

**Comment by inversionhourglass** [comment]
If you want the span id to be continuous, then you need to standardize programming and await the async method. If you really don’t need to wait for the task to complete, you can manually create a segment for the async task. My subsequent pull request will include the extension related to threading. The purpose is to It is convenient to manually create asynchronous segments. And the merge logic that will be submitted later is to make the data as complete as possible and the span id more continuous.

**Comment by wu-sheng** [comment]
As Java agent is super mature and Java/.Net shares a similar VM/agent mechanism, you could refer to their APIs.

https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/java-plugin-development-guide/#async-span-apis

There are two cases of cross threads, span could cross threads to have accurate duration/status. And trace context would not because ContextSnapshot is designed for this.

**Comment by wu-sheng** [comment]
All concepts I mentioned are in the Java agent. .Net agent is not that strong to implement all concepts.

[ContextSnapshot](https://github.com/apache/skywalking-java/blob/bd7912106aede5f79dbcfcdafe5c13c4378d8629/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextManager.java#L153-L159)

Take a look at how the Java agent did. 

A suggestion/tip, what you are facing in .net agent would be alone and that special. In 99.99% of cases, Java agent faces and dealt with these scenarios.

**Comment by inversionhourglass** [comment]
由于逻辑比较复杂，用半翻译的英文我可能说不太清，我直接用中文描述了。

.NET和Java是很像，但也有很多不同，也正是这些不同点，成为了APM链路构造的一个难点。
我看了AsyncSpan的逻辑，`TracingContext`会等到所有`AsyncSpan`完成后再提交，这个逻辑在我这边有类似的实现，我使用的是 [AsyncSpanCombiner](https://github.com/inversionhourglass/SkyAPM-dotnet/blob/master/src/SkyApm.Core/Tracing/AsyncSpanCombiner.cs) ，对于有异步span没有完成的，会延迟几秒（默认五秒）后进行segment合并，再推送到服务端。那能不能改成java实现的那种，直接等待异步span完成后再提交？理想情况下是可以的，但现实情况可能并不允许。因为我们不知道异步任务需要多久完成，可能很快也可能很久，特别是在.NET中（后面介绍），我认同APM没有必要做成完全实时的，所以我创建了 AsyncSpanCombiner ，但我认为这个延迟还是要有个限度，skywalking有告警功能，有一些重要的告警我们可能不能延迟几十秒甚至几分钟才接收到，如果数据延迟无法上报，自然也就无法及时产生告警，所以 AsyncSpanCombiner  我默认限制了5秒，并且可以配置。

上面我又说到异步任务可能需要很久完成，特别是在.NET中，这是由于.NET中异步编程导致的，在.NET中async/await会导致线程切换，处理一个请求可能切换多个线程，唯一为了保存整个请求的span数据，.NET只能选用`AsyncLocal`，而Java不存在这种问题，所以可以直接使用`ThreadLocal`，这个区别导致.NET和Java面临着完全相反的局面，比如以下代码：
```java
public void m1() {
  new Thread(this::m2).start();
}
public void m2() {
}
```
在Java中，由于m1和m2跨线程了，所以需要想办法将两个方法产生的segment进行关联，而在.NET中`AsyncLocal`不仅能在异步编程中传递数据，对于手动创建的线程也同样有效，所以m2会直接取到m1的segment，初看这种特性似乎更方便更省事，但实际上却有麻烦的地方。上面的这个例子对Java和.NET各有什么优缺点呢：
**Java：**
优点：m1和m2的segment各自提交，不必等待，实时性好
缺点：默认m2和m2无法关联，需要额外想办法
**.NET：**
优点：m2直接与m1在同一个segment里，关联性好，不需要额外处理
缺点：既然是手动创建的线程，那么就有可能是一个长任务，如果你去等待一个长任务完成后再提交数据，那么实时性将非常差
前面说的两个完全相反的局面就是Java需要考虑如何去关联不同线程的segment，而.NET需要考虑如何干掉不需要的关联。

.NET在异步编程上还有各种各样的情况，但如果按照Java的这种方式，那么主要的问题就是——真的要去等异步span完成吗？
编程人员的水平不一，我看过很多奇怪的代码，上面的那个例子中直接线程里while死循环也是有的。

我现在提交的实现方式就是不去等异步span完成，通过 AsyncSpanCombiner 兼容能够快速完成异步操作的情况。后面再提供[线程类相关的扩展](https://github.com/inversionhourglass/SkyAPM-dotnet/tree/master/src/SkyApm.Threading/System/Threading)来支持将长任务单独创建一个segment进行关联。

**Comment by wu-sheng** [comment]
I am not asking to let all spans to be async and wait, I am not suggesting duration relative spans.
Those concepts(snaptshot and async span) are being used together, but you treat them opposite.
What your mentioned is not special in .net, every language has similar case.

**Comment by liuhaoyang** [comment]
I don't recommend introducing a new Span concept on the API. We can consider using new data structures, such as stacks or atomic operations, to ensure the continuity of segments ...

**Comment by wu-sheng** [comment]
BTW, segments sorted in UI could be aligned by start time(we may not support it for now).  Span ID should not be missed from 0 to N in any case, this is not for .net or Java. If you are challenging this, then you face a whole project scope concern.  A dozen of agents/SDKs existing are following this logic, .Net is not that special.

FYI @Fine0830 We may consider this. `segments sorted in UI could be aligned by start time`.

**Comment by inversionhourglass** [comment]
上一个回答我做了一些解释，这一个我说一下我的疑问。

为什么要求spanid必须连续？如果是rocketbot-ui里相同的逻辑，用来检查span的完整性，那我觉得没有必要，使用parent span id检查所有span各自的父级span是否存在就已经保证数据基本完整了，因为即使验证1-N的span是否全都都在也无法完全确保数据完整，因为你无法确定spanid是否真的只到N，这个验证逻辑也只是保证数据基本完整。
要求spanid必须连续其实也限制了client的一定自由发挥空间，这就不允许客户端丢弃生成的一些spanid以及span了，比如类似java提供了`Trace`注解，可以通过注解来方便创建localspan，这个注解有可能被开发人员滥用，比如一个循环里调用了一个方法，那么方法上有`Trace`注解，这可能会生成特别多数据，我们可以通过配置的形式丢弃掉这些庞大而冗余的数据，而不需要修改代码重新发布，这种情况就是丢弃部分已经生成的spanid，但数据通过parent span id关联还是完整的。这只是我随便举的一个例子，我是想如果不是哪里有强逻辑需要spanid连续，那么就没有必要去这么要求，应该给与客户端一定自由发挥的空间。

segment乱序只是我希望使用span为主结构的原因之一，我认为为每一个span单独创建一个segment从概念上来讲不合理，从数据方面考虑segment是包含traceid、segmentid、entrypoint等系列额外数据的，每个span一个segment是会产生大量冗余数据的，.NET现在使用segment为主体结构应该也是因为遇到我上一个回答中类似的问题，使用segment来解决很聪明，这样能够保证数据采集正常，也能保证一定的关联系，但也存在由于segment id的结构不具备可排序性导致的乱序问题以及我刚面说到的其他问题。另外我觉得以开始时间进行排序的做法和.NET里用segment作为主结构是相同的思路，只能够解决部分的问题，开始时间并不是一个完全可靠的排序依据，多个异步任务同一毫秒开始也是很常见的。

每个语言都有每个语言的特点，你认为.NET的异步编程所遇到的情况并没有什么特殊，或许是我的经验和能力不足还想不出更好的方案，如果你有span结构的方案，我真切的希望你能实现一个span结构的客户端，维持现在的segment结构并不是一个好的选择。

**Comment by wu-sheng** [comment]
I am not sure I can follow you.
You are new in this community, and challenging the whole structure without deeply thinking. You are only staying in a status, (I want), this is really a bad practice in a diverse and hundreds contributors community.

Such as simply trace annotation, you want a xml/yaml config, Java agent also has that. Some one prefer annotations, others like no code change. This is what we as a community are facing.

You always put your preferences in high priority, but don't listen and take a step back to think more about others in this whole discussion context.

Also, @liuhaoyang built this in 4 years, even before you knew this exists. You should be patient and unassertive. You should know, he has fully community and project support due to the credit nd commitments he did.

It is easy to ask for changes, but the whole community afford the consequence. SkyWalking users are various globally, we don't want an agent driving the whole community level impact, because simply it isn't worth.

---

I put many points above, I know there are very few Chinese initiated open source projects really diverse, but we are, and very. So, you can't use your preview experiences  when you do your own project or company's project.

**Comment by inversionhourglass** [comment]
的确，我没有完整的看你java的全部逻辑，但对于你说的AsyncSpan和ContextSnapshot我想我应该并没有理解错误，CrossThreadCarrier与ContextSnapshot是相同的，在知道有异步不需要等待的span时通过ContextManager.capture创建ContextSnapshot，然后再异步任务中通过ContextManager.continued与外部segment进行关联，类似下面的用法：
```java
ContextSnapshot snapshot = ContextManager.capture();
new Thread(()->{
ContextManager.continued(snapshot);
})
```
而AsyncSpan是用于有异步任务，并且你知道异步任务很快能够结束的情况，TraceContext内部持有一个计数，统计未完成的AsyncSpan数量，在最外层Span完成时，如果还有AsyncSpan没有完成，那么会这个TraceContext不会提交，每个AsyncSpan在完成时也会检查所有AsyncSpan和最外层span是否已完成，如果已完成则提交。
.NET这边的问题在于，在异步编程里，我无法确定一个异步方法开发人员是否会调用await，无法区分长任务与短任务，从而选择使用ContextSnapshot还是AsyncSpan。

我知道这个改动很大，所以如果你看了我第一个PR的描述应该能知道，为了让这个改动不会对现在的逻辑产生影响，我增加了配置项以及兼容的方法接口，默认还是以segment为主结构，只是给了一种额外的选择，可以通过配置切换到以span为主的结构，后续如果其他人对span结构有更好的想法也更方便进行迭代。

**Pull request closed without merging**
