### PR TITLE
fix: AsyncQueueSkyApmLogDispatcher._offset is not correct exactly in muti threads

### PR DESCRIPTION
**Pull request by sampsonye**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
#514 
___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by liuhaoyang** [comment]
If the offset is not reset in flush, once the offset is larger than the config.QueueSize, no more LogRequest will be processed.

**Comment by liuhaoyang** [comment]
I think there should be another better way to handle the reset of offset instead of removing directly

**Comment by sampsonye** [comment]
> If the offset is not reset in flush, once the offset is larger than the config.QueueSize, no more LogRequest will be processed.

i can not find whenever the offset do not equals theQueueSize

can you show some case than they not equal?

**Comment by liuhaoyang** [comment]
> i can not find whenever the offset do not equals theQueueSize

Each time a LogerRequest enters Dispatch, the offset will be incremented [AsyncQueueSkyApmLogDispatcher.cs#L64](https://github.com/SkyAPM/SkyAPM-dotnet/blob/main/src/SkyApm.Core/Transport/AsyncQueueSkyApmLogDispatcher.cs#L64)

**Review by liuhaoyang — APPROVED** [review]

**Pull request merged**
