### PR TITLE
Remove support for .net framework

### PR DESCRIPTION
**Pull request by yang-xiaodong**

### CODE REVIEW

**Comment by ElderJames** [comment]
Are you sure we don't support the .NET Framework?

**Comment by yang-xiaodong** [comment]
> Are you sure we don't support the .NET Framework?

According to the description of the  #325,#362 by @liuhaoyang that we currently don't support the .NET Framework very well,  so I think we will no longer to support in the future.

What do you think of this?  @liuhaoyang  @ElderJames  @snakorse

**Comment by zeaposs** [comment]
FYI, I've been fixing bugs in ASP .NET Agent and I have it working on my local machine. I wanted to add PR within few days, so please let me know, if ASP.NET fate is really sealed ;) .

**Comment by ElderJames** [comment]
@yang-xiaodong I don't think so. It still makes sense to keep the support for .Net framework, even if it's just support some simple features.

**Comment by ElderJames** [comment]
@zeaposs Thank you for that.Your contribution would be greatly appreciated.

**Comment by zeaposs** [comment]
@ElderJames I've started code cleanup and I should be able to commit all changes on my fork today. There are four main issues, that need fixing: IConfiguration, Nito async, tracing handler thread freeze and vanishing SegmentContext. I'll create PR with proper description after commiting all changes on my [fork](https://github.com/zeaposs/SkyAPM-dotnet).

**Comment by zeaposs** [comment]
Here's the PR: https://github.com/SkyAPM/SkyAPM-dotnet/pull/366

**Comment by yang-xiaodong** [comment]
Ok , it looks like this PR can be closed

**Pull request closed without merging**
