### PR TITLE
Use config to control log report level and enrich log message

### PR DESCRIPTION
**Pull request by inversionhourglass**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [ ] New feature provided
- [x] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
1. Append Exception detail into log message if exception is not null.
2. Now we can use config key `SkyWalking::LogCollector::Level` to control log collect level. It's useful if someone does not wanna collect log data or only want to collect error log data.
```json
{
  "SkyWalking": {
    "LogCollector": {
      "Level": "Information" // default
    }
  }
}
```

### CODE REVIEW

**Comment by liuhaoyang** [comment]
For the configuration of the Diagnostics plugins, it is recommended to use the Diagnostics subsection. 
```
{
  "SkyWalking": {
    "Diagnostics": {
      "Logging": {
          "CollectLevel": "Information"
       }
    }
  }
}
```

**Comment by liuhaoyang** [comment]
> Log is a top level data type same as trace and metric. Uses a top level configuration section maybe better. All diagnostics component of logger(mslogging, serilog, etc..) should implement this config by themself.

The core only provides the ability to report logs to sw, and collect logs through the Diagnostics.Logging package, configuration should also be associated with Diagnostics.Logging.

**Comment by inversionhourglass** [comment]
I'll change the code. But I still have reservations. For core concepts such as log, some basic configurations can be defined before the specific implementation. These configurations depend on the concept rather than the implementation.

---

代码我会按你的建议来改，但我仍然保留我的意见。像log这种核心概念，在具体实现之前就可以定义一些基本配置，这些配置是依赖于概念而不是依赖于实现。

**Review by liuhaoyang — APPROVED** [review]
LGTM

**Pull request merged**
