### PR TITLE
Can manual clear current context or make the context relation weakly.

### PR DESCRIPTION
**Pull request by inversionhourglass**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.
If any one of `EntrySegmentContext` or `LocalSegmentContext` already exists in the current thread, then create a new thread from this thread to executes a long running task(infinite loop). The trace data generated in this thread will use the `traceId` generated in the first thread, so the data of this `traceId` will increase infinitely.
如果在当前线程已经存在`EntrySegmentContext`或`LocalSegmentContext`中的任意一个的情况下新建一个无限循环执行任务的线程，那么该线程中产生的trace数据将使用第一个线程中产生的`traceId`，那么这个`traceId`的数据将无限增加。
```csharp
[HttpGet]
public async Task Test()
{
    Task.Factory.StartNew(async () =>
    {
        while (true)
        {
            // The trace data generated by this request will use the `traceId` generated by the external thread
            await new HttpClient().GetAsync("http://localhost:5002/api/delay/1000");
            await Task.Delay(2000);
        }
    }, TaskCreationOptions.LongRunning);

    await new HttpClient().GetAsync("http://localhost:5002/api/delay/1000");
}
```

This PR adds two new methods on `ITracingContext`:
- `void ClearContext()` Simply clear `EntrySegmentContext`, `LocalSegmentContext` and `ExitSegmentContext` in current thrad.
- `void WeakenContext()` Do the same thing as `ClearContext`, but the external thread trace id will be save to tags.
```csharp
[HttpGet]
public async Task Test()
{
    Task.Factory.StartNew(async () =>
    {
        _tracingContext.ClearContext();
        // _tracingContext.WeakenContext();
        while (true)
        {
            await new HttpClient().GetAsync("http://localhost:5002/api/delay/1000");
            await Task.Delay(2000);
        }
    }, TaskCreationOptions.LongRunning);

    await new HttpClient().GetAsync("http://localhost:5002/api/delay/1000");
}
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why do we clear context manually? What are the use cases?

**Comment by wu-sheng** [comment]
> If any one of EntrySegmentContext or LocalSegmentContext already exists in the current thread, then create a new thread from this thread to executes a long running task(infinite loop).

This means bug happened, and there is tracing context leak. Clearing the context doesn't help in the right way. We should fix bugs, rather than ignoring this and forcely clear.

**Comment by inversionhourglass** [comment]
> This means bug happened, and there is tracing context leak. Clearing the context doesn't help in the right way. We should fix bugs, rather than ignoring this and forcely clear.

It's may not a bug, becasue .NET use `AsyncLocal` to save the `TracingContext`, it's automatically passed across threads.

**Comment by wu-sheng** [comment]
I don't know all the datails of .net agent. But once the thread is being switched out for reuse in another context, the tracing context should be removed automatically.
Such as in Java agent case, ref https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/java-plugin-development-guide/#async-span-apis

There are steps for a span for async calling. Once step <2> is done(in the same thread), the current span has been poped out of thread context. Further `asyncFinish` would tag the segment ready to send to OAP. 
Segment actually is not always as same as the tracing context.

**Comment by inversionhourglass** [comment]
> But once the thread is being switched out for reuse in another context, the tracing context should be removed automatically.

We cannot remove the context automatically, all segments will get a new trace id if we do that.

This is not about how to complete the span across threads, it is about how to store and associate multiple contexts.
In .NET, thread switching happens all the time, if you want the intrusion of the agent's operation to be as small as possible, `AsyncLocal` is a good choice. As long as `AsyncLocal` is used, we cannot automatically complete the removal operation, it must be handled manually.
```csharp
public async Task Test()
{
  // case 1, manual create a long running task with infinite loop and without await 
  Task.Run(() => {
    // thread changed. Because this is a long running task with infinite loop, so we should remove the context and generate a new trace id
  });

  // case 2, manual create a short task with await
  await Task.Run(() => {
    // thread changed. Because there is an await operation outside, so we cannot remove the context and we should use the same trace id
  });

  // case 3, the general await scenario
  await HttpCall();
  // thread changed. Because there is an await operation above, so we cannot remove the context and we should use the same trace id

  // case 4, manual create a short task and await later
  var t1 = Task.Run(() => {
    // thread changed. Because it will eventually await, so we cannot remove the context and we should use the same trace id
  });
  var t2 = HttpCall();
  await Task.WhenAll(t1, t2);
}
```

总的来说，由于我们现在是使用`AsyncLocal`来存储`TracingContext`，加上.NET异步多样的写法，我们无法判断什么时候切换线程时需要清除Context什么时候不需要清除，如果每次切换线程时都将Context传递到新的线程中并清除原来线程中的Context，那么上面代码中case1和case4都无法产生正确的Trace数据。
其实像这次PR中提到的场景是平时比较少见的，但是一旦出现，那么这个trace id的关联数据就会无限增加，现在能够想到的办法就是针对这种少数的场景进行手动处理。

**Comment by wu-sheng** [comment]
Why we don't need clear manually, because you will never know when to clear. Unless, we defines all entrances, clearly, we can't.

**Comment by wu-sheng** [comment]
I am not saying you have to follow Java module, but the idea has to be proved that, we know how segment begins, and how to close.
I had known, .net segment is fragmented, complex thread module made it.
The key part of being an auto instrument agent is, making things automatically. Otherwise, we just build a SDK.

**Comment by inversionhourglass** [comment]
In my opinion, solving a problem is more important than pursuing full automation. I can't make all things automatically, maybe I should create a issue not a pr.

**Comment by wu-sheng** [comment]
In the open source, we are forcing to resolve issue, rather than providing half patch.

It is better you could start a discussion(or issue) about how segment open and close currently, and what we could do to enhance, also invite @liuhaoyang in.

**Pull request closed without merging**
