### PR TITLE
Fixed package references for .NET Core 2.1 dependencies

### LINKED ISSUE #419: Can't setup to SkyAPM.Agent.AspNet v1.3.0 to netcore2.2 project
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
I setup SkyAPM.Agent.AspNet v1.3.0 to netcore2.2 project, but it requires netcore3.1.
Then I tried to setup SkyAPM.Agent.AspNet v1.3.0 to a standard 2.0 project, but there is a dependency conflict between skyapm v1.3.0 and my project.
image

So what should I do to make it works?

### PR DESCRIPTION
**Pull request by ElderJames**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

Fixed #419 

___
### Bug fix
- Bug description.

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Review by snakorse — APPROVED** [review]

**Comment by wu-sheng** [comment]
CI fails. Could you recheck?

**Comment by ElderJames** [comment]
I will fix it later.

**Comment by liuhaoyang** [comment]
.NET Core 2.1 is no longer supported, I will close this pull request first.

**Comment by liuhaoyang** [comment]
.NET Core 2.1 is no longer supported, I will close this pull request first.

**Pull request closed without merging**
