### PR TITLE
fix CreateExitSegment.GetParentSegmentContext(SpanType.Exit) bug

### PR DESCRIPTION
**Pull request by Ahoo-Wang**
Please answer these questions before submitting pull request

- Why submit this pull request?
- [x] Bug fix
___
### Bug fix
- Bug description.

image

---->>>>>

image

### CODE REVIEW

**Comment by liuhaoyang** [comment]
Please resolve the code conflict first

**Comment by caozhiyuan** [comment]
i feel contextAccessor.Context (AsyncLocal ConcurrentStack) may have some error .
when thread1 first push in stack and thread2 second push in stack, but thread2 complete first will what happen?
opentracing asyncsocpe can as reference.  Now , when taskcontinue will leak context restore (such as sqlclient) . @liuhaoyang

**Comment by liuhaoyang** [comment]
> i feel contextAccessor.Context (AsyncLocal ConcurrentStack) may have some error .
> when thread1 first push in stack and thread2 second push in stack, but thread2 complete first will what happen?
> opentracing asyncsocpe can as reference. Now , when taskcontinue will leak context restore (such as sqlclient) . @liuhaoyang

The implementation of LocalSegmentContextAccessor is limited by the DiagnosisSource model. In the profiler model, we can use asyncScope to pass the trace context in an asynchronous function.

**Comment by caozhiyuan** [comment]
@liuhaoyang  i descibe above wrong ( thread1、thread2 , should  task1、task2 - method not mark async  https://github.com/caozhiyuan/SkyAPM-dotnet/blob/contextAccessor/sample/SkyApm.Sample.Backend/Controllers/AppsController.cs#L79 test2) , ignore it if always use async await (because asyncmethod builder will ExecutionContext.RestoreChangedContextToThread ) . 
AppsController test1 https://github.com/caozhiyuan/SkyAPM-dotnet/blob/contextAccessor/sample/SkyApm.Sample.Backend/Controllers/AppsController.cs#L54 show sqlclient DiagnosisSource  continue problem

**Pull request closed without merging**
